version: "3.2"

services:
  api:
    build: ./images/api
    volumes:
      - ./images/api/src:/usr/app/src
    environment:
      NODE_ENV: "development"
      PGHOST: "store" # Use the service name here
    env_file:
      - ./config/.env.dev
    depends_on:
      store:
        condition: service_healthy

    user: "node"
    command: npm run test-watch

  store:
    container_name: store
    image: postgres:latest
    restart: always
    env_file:
      - ./config/.env.dev
    ports:
      - "5432:5432"
    volumes:
      - ./_backup:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"] # Health check command to verify database availability
      interval: 10s # Check the health status every 10 seconds
      retries: 5 # Number of retries before considering it unhealthy
      start_period: 20s # Wait 20 seconds after the container starts before starting checks
