version: "3.2"

services:
  api:
    build: ./images/api
    environment:
      - NODE_ENV=production
    user: "node"
    command: npm start

  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - ./config/.env.prod
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: ["postgres", "-c", "log_statement=all"]
